/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_unisa_earify_algorithms_lbp_LBPNativeLibrary */

#ifndef _Included_it_unisa_earify_algorithms_lbp_LBPNativeLibrary
#define _Included_it_unisa_earify_algorithms_lbp_LBPNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_unisa_earify_algorithms_lbp_LBPNativeLibrary
 * Method:    extractFeatures
 * Signature: (Ljava/lang/String;II)[I
 */
JNIEXPORT jintArray JNICALL Java_it_unisa_earify_algorithms_lbp_LBPNativeLibrary_extractFeatures
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
